### PR TITLE
Try Windows without CppADCodeGen

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by jcarpent** [comment]
Concerning this issue, I had to:
1. Add v142 as testing (this is the default Visual Studio compiler on Windows)
2. Fix issue in the conda generated cppad package as it was using debug modes due to https://github.com/coin-or/CppAD/issues/113
3. Fix issue with CppAD when the compiler is not the default Windows but rather clang. See https://github.com/coin-or/CppAD/pull/114 for more details.

**Comment by jcarpent** [comment]
This should be passing now.

**Review by proyan — APPROVED** [review]
Thanks @jcarpent for the quick fixes!

**Comment by jcarpent** [comment]
I've just reintroduced CppADCodeGen. I hope it will work.
I will then try to remove the useless debug features.

**Comment by jcarpent** [comment]
Regarding the flow of errors with CppADCodeGen, ON we need to first fix CppADCodeGen before.
I will deactivate this feature.

**Comment by jcarpent** [comment]
After the CI passed, we can merge.
@proyan Could you enable Windows on conda?
It would also be nice to expose the flags in Python to know with CppADCodeGen is available.

**Comment by proyan** [comment]
We can wait for https://github.com/coin-or/CppAD/pull/114 and hopefully a new release before putting codegen in windows. I'll try a local build to verify that is the only issue remaining.

**Comment by jcarpent** [comment]
> We can wait for [coin-or/CppAD#114](https://github.com/coin-or/CppAD/pull/114)

In fact, we should not wait for that. This is not needed I think currently to move forward.

**Pull request merged**
