### PR TITLE
define PYCPPAD_SCALAR_TYPE=double in CMakeLIsts

### PR DESCRIPTION
**Pull request by proyan**

### CODE REVIEW

**Review by jcarpent — COMMENTED** [review]
I don't think this helps so much. I would not change it at this stage.

**Comment by proyan** [comment]
It would be useful to keep the scalar type at a single location. This might be in a header file, or the CMakeLists. Do you see any issues with defining it in the CMakeLists?

**Comment by jcarpent** [comment]
Yes, if someone wants to link to the lib. It is not very elegant and practical. In addition, the ABI compatibility will be break if we need to use two different scalar types. 
I would say, the function `enablePyCppAD` should be rather templatized with a default template value. This is the most generic approach.

**Comment by proyan** [comment]
Ill leave it as is for the time being. But we would have to rethink the library structure at a future date. Ill close this PR.

**Pull request closed without merging**
