### PR TITLE
ci: setup gitlab CI

### PR DESCRIPTION
**Pull request by nim65s**
another try at #17

### CODE REVIEW

**Comment by nim65s** [comment]
Ok, I got it. the notification doesn't work, because it's not using https://github.com/apps/gepetto-dashboard to push the status, but a token from @hrp2-14. Can this bot be added in the organisation / project ?

**Comment by proyan** [comment]
I just sent an invitation. Who has access to the bot?

**Comment by jcarpent** [comment]
@nim65s What is the current status?

**Comment by proyan** [comment]
@nim65s Do you still have the invitation for hrp2 bot, or do you want me to send it again?

**Comment by nim65s** [comment]
It works now, thanks :)

**Pull request merged**
